spring:
  application:
    name: log-monitor-application
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8021
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    org:
#      springframework: debug
#    com:
#      baomidou: debug
#      apache: debug
log:
  monitor:
    levels: all
