server:
  port: 11613
spring:
  application:
    name: nosql-mongodb
  # MongoDB 缓存配置
  data:
    mongodb:
      # 主机
      host: 127.0.0.1
      # 端口
      port: 27017
      # 连接数据库
      database: test
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver