spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#logging:
#  level:
#    org:
#      springframework: debug
#      apache: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
prefix-app:
  name: hpp
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 3
    #basedir: D:/app/vshx-boot-web
  port: 8080
  connection-timeout: 180000ms
  servlet:
    context-path: /
