
package webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "pmsStandardLogisticsSyn",
        targetNamespace = "http://pms.changan.com.cn",
        wsdlLocation = "http://183.66.200.161:12090/TESTPMS/service/pmsStandardLogisticsSyn?wsdl")
public class PmsStandardLogisticsSyn
    extends Service
{

    private final static URL PMSSTANDARDLOGISTICSSYN_WSDL_LOCATION;
    private final static WebServiceException PMSSTANDARDLOGISTICSSYN_EXCEPTION;
    private final static QName PMSSTANDARDLOGISTICSSYN_QNAME = new QName("http://pms.changan.com.cn", "pmsStandardLogisticsSyn");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://183.66.200.161:12090/TESTPMS/service/pmsStandardLogisticsSyn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PMSSTANDARDLOGISTICSSYN_WSDL_LOCATION = url;
        PMSSTANDARDLOGISTICSSYN_EXCEPTION = e;
    }

    public PmsStandardLogisticsSyn() {
        super(__getWsdlLocation(), PMSSTANDARDLOGISTICSSYN_QNAME);
    }

    public PmsStandardLogisticsSyn(WebServiceFeature... features) {
        super(__getWsdlLocation(), PMSSTANDARDLOGISTICSSYN_QNAME, features);
    }

    public PmsStandardLogisticsSyn(URL wsdlLocation) {
        super(wsdlLocation, PMSSTANDARDLOGISTICSSYN_QNAME);
    }

    public PmsStandardLogisticsSyn(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PMSSTANDARDLOGISTICSSYN_QNAME, features);
    }

    public PmsStandardLogisticsSyn(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PmsStandardLogisticsSyn(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PmsStandardLogisticsSynPortType
     */
    @WebEndpoint(name = "pmsStandardLogisticsSynHttpSoap11Endpoint")
    public PmsStandardLogisticsSynPortType getPmsStandardLogisticsSynHttpSoap11Endpoint() {
        return super.getPort(new QName("http://pms.changan.com.cn", "pmsStandardLogisticsSynHttpSoap11Endpoint"), PmsStandardLogisticsSynPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PmsStandardLogisticsSynPortType
     */
    @WebEndpoint(name = "pmsStandardLogisticsSynHttpSoap11Endpoint")
    public PmsStandardLogisticsSynPortType getPmsStandardLogisticsSynHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://pms.changan.com.cn", "pmsStandardLogisticsSynHttpSoap11Endpoint"), PmsStandardLogisticsSynPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PMSSTANDARDLOGISTICSSYN_EXCEPTION!= null) {
            throw PMSSTANDARDLOGISTICSSYN_EXCEPTION;
        }
        return PMSSTANDARDLOGISTICSSYN_WSDL_LOCATION;
    }

}
