
package webservice.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "pmsStandardLogisticsSynPortType", targetNamespace = "http://pms.changan.com.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PmsStandardLogisticsSynPortType {


    /**
     * 
     * @param loginUserName
     * @param password
     * @param logisticsCarriers
     * @param trackDataList
     * @return
     *     returns webservice.service.PmsAddTrackDataListVo
     * @throws PmsStandardLogisticsSynException_Exception
     */
    @WebMethod(action = "urn:addTrackDataList")
    @WebResult(targetNamespace = "http://pms.changan.com.cn")
    @RequestWrapper(localName = "addTrackDataList", targetNamespace = "http://pms.changan.com.cn", className = "webservice.service.AddTrackDataList")
    @ResponseWrapper(localName = "addTrackDataListResponse", targetNamespace = "http://pms.changan.com.cn", className = "webservice.service.AddTrackDataListResponse")
    public PmsAddTrackDataListVo addTrackDataList(
        @WebParam(name = "logisticsCarriers", targetNamespace = "http://pms.changan.com.cn")
        String logisticsCarriers,
        @WebParam(name = "loginUserName", targetNamespace = "http://pms.changan.com.cn")
        String loginUserName,
        @WebParam(name = "password", targetNamespace = "http://pms.changan.com.cn")
        String password,
        @WebParam(name = "trackDataList", targetNamespace = "http://pms.changan.com.cn")
        List<TrackPO> trackDataList)
        throws PmsStandardLogisticsSynException_Exception
    ;

    /**
     * 
     * @param password
     * @return
     *     returns java.lang.String
     * @throws PmsStandardLogisticsSynException_Exception
     */
    @WebMethod(action = "urn:getKey")
    @WebResult(targetNamespace = "http://pms.changan.com.cn")
    @RequestWrapper(localName = "getKey", targetNamespace = "http://pms.changan.com.cn", className = "webservice.service.GetKey")
    @ResponseWrapper(localName = "getKeyResponse", targetNamespace = "http://pms.changan.com.cn", className = "webservice.service.GetKeyResponse")
    public String getKey(
        @WebParam(name = "password", targetNamespace = "http://pms.changan.com.cn")
        String password)
        throws PmsStandardLogisticsSynException_Exception
    ;

    /**
     * 
     * @param loginUserName
     * @param password
     * @param trackPO
     * @param logisticsCarriers
     * @return
     *     returns webservice.service.PmsAddTrackDataVo
     */
    @WebMethod(action = "urn:addTrackData")
    @WebResult(targetNamespace = "http://pms.changan.com.cn")
    @RequestWrapper(localName = "addTrackData", targetNamespace = "http://pms.changan.com.cn", className = "webservice.service.AddTrackData")
    @ResponseWrapper(localName = "addTrackDataResponse", targetNamespace = "http://pms.changan.com.cn", className = "webservice.service.AddTrackDataResponse")
    public PmsAddTrackDataVo addTrackData(
        @WebParam(name = "logisticsCarriers", targetNamespace = "http://pms.changan.com.cn")
        String logisticsCarriers,
        @WebParam(name = "loginUserName", targetNamespace = "http://pms.changan.com.cn")
        String loginUserName,
        @WebParam(name = "password", targetNamespace = "http://pms.changan.com.cn")
        String password,
        @WebParam(name = "trackPO", targetNamespace = "http://pms.changan.com.cn")
        TrackPO trackPO);

}
