
package webservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "pmsStandardLogisticsSynException", targetNamespace = "http://pms.changan.com.cn")
public class PmsStandardLogisticsSynException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PmsStandardLogisticsSynException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PmsStandardLogisticsSynException_Exception(String message, PmsStandardLogisticsSynException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PmsStandardLogisticsSynException_Exception(String message, PmsStandardLogisticsSynException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.service.PmsStandardLogisticsSynException
     */
    public PmsStandardLogisticsSynException getFaultInfo() {
        return faultInfo;
    }

}
