spring:
  data:
    cassandra:
      read-timeout: 1s
  application:
    name: mybatis-intercepter
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    async:
      request-timeout: 20S
server:
  tomcat:
    connection-timeout: 1000
  port: 8080
  servlet:
    session:
      timeout: 60s
#logging:
#  level:
#    org:
#      springframework: debug
#      apache: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml
